// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwcxngmrzzshkehloqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Y3huZ21yenpzaGtlaGxvcXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Nzk5OTAsImV4cCI6MjA2ODI1NTk5MH0.vpK4el33PHVXrJcvucKhyrM2tGG43z-FuAmFmHc86Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});